org: menglinmaker
app: grocery-suggester
service: webscrape
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x

functions:
  getProductLink:
    name: grocery-suggester-getProductLink
    description: Gets links to grocery products
    timeout: 540
    handler: getProductLink.serverlessHandler
    events:
      - httpApi:
          path: /
          method: get
      - schedule: cron(0 9 * * SAT *)

plugins:
  - serverless-offline
  - serverless-plugin-typescript
