service: Grocermatic

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-2
  stage: dev

plugins:
  - serverless-esbuild

custom:
  esbuild:
    bundle: true
    minify: true


functions:
  getProductLink:
    handler: getProductLink.serverlessHandler
    timeout: 900
    description: Gets links to grocery products
